### ISSUE TITLE
Tinn-R syntax highlighting lost after \"

### ISSUE THREAD

**Issue by dmcp** [jcfaria/Tinn-R#1]
Tinn-R ver 3.0.3.6
OS Widows 7 Prof SP1

Tinn-R loses its syntax highlighting after the character sequence \"
 Hopefully the attached image will show you what I mean. It seems that, within Tinn-R, the backslash does not escape the double quote. This is a minor annoyance and should be treated as such. A work around exists - I can just use single quotes (as shown in the attached), it is just not my preferred option. This same behaviour was also apparent in Tinn-R 3.0.2.

I have not included details on my R installation, or the log outputs  - my (uninformed) opinion is that they are probably not relevant. If this info is desirable I am happy to forward it.

If you agree that this is a bug (and worth the effort), please put it on the list of things to fix - with a suitably low priority.

![tinn-r_scrn](https://cloud.githubusercontent.com/assets/6426238/3581159/83dc63ba-0be5-11e4-9e21-26f0cc919026.png)
#### End of report - - waffle follows

Apologies for not going through google groups as you request in help. I refuse to supply google with the level of information they want for me to sign up.

Many thanks for Tinn-R. I've been using it for some years, and it makes life with R much, much easier...

Dale.

**Comment by jcfaria** [comment]
Dear Dale,

Many thanks for pointing it out!
We are working to release a new version and we will try to fix it.

All the best,
J.C.Faria
